#Machine Learning Assignment#

####***author:*** Sonat####
####***date:*** 14 Oct 2015###
####***output:*** html_document###

### Background ###

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 

### Data ### 

The training data for this project are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

### Goal ###

The goal of your project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set.

### Execution ###

First we load the necessary libraries, plant seed for reproduceability and load data. 

pmlTrain <- read.csv(url("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"),stringsAsFactors = FALSE)

pmlTest <- read.csv(url("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"),stringsAsFactors = FALSE)

``` {r message=FALSE, warning=FALSE}
library(knitr)
library(caret)

set.seed(123)

pmlTest <- readRDS("pmlTest.rds")
pmlTrain <- readRDS("pmlTrain.rds")

dim(pmlTest)
dim(pmlTrain)

training_dt <- as.matrix(sapply(pmlTrain,typeof))
training_dt_char <- which(training_dt[,1] == "character")
training_dt_char
training_dt_char <- setdiff(training_dt_char,c(160))
pmlTrain <- pmlTrain[,-training_dt_char]
pmlTrain <- pmlTrain[,colSums(is.na(pmlTrain)) == 0]

inTrain <- createDataPartition(y=pmlTrain$classe,p=0.90,list=FALSE)
training <- pmlTrain[inTrain,]
testing <- pmlTrain[-inTrain,]

training$classe <- as.factor(training$classe)
testing$classe <- as.factor(testing$classe)

modFit <- train(classe ~., data=training, method="lda")
modFit

pred <- predict(modFit,testing,type="raw")
confusionMatrix(pred,testing$classe)

pred2 <- predict(modFit,pmlTest,type="raw")
pred2
```

